Document: jabberd2
Title: Debian jabberd2 Manual
Author: <insert document author here>
Abstract: This manual describes what jabberd2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jabberd2/jabberd2.sgml.gz

Format: postscript
Files: /usr/share/doc/jabberd2/jabberd2.ps.gz

Format: text
Files: /usr/share/doc/jabberd2/jabberd2.text.gz

Format: HTML
Index: /usr/share/doc/jabberd2/html/index.html
Files: /usr/share/doc/jabberd2/html/*.html
